config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  devise_scope :user do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :new, :create, :show] do
    resources :boards, only: [:index, :new, :create, :show]
  end

  resources :boards, only: [:index, :show, :new, :create] do
    resources :users, only: [:index, :new, :create, :show]
  end

  resources :boards, only: [:index, :new, :create, :show] do
    resources :bookings, only: [:index, :new, :create, :show]
  end

  resources :users, only: [:index, :new, :create, :show] do
    resources :bookings, only: [:index, :new, :create, :show]
  end

  resources :bookings, only: [:index, :new, :create, :show] do
    resources :users, only: [:index, :new, :create, :show]
  end

  resources :users, only: [:index, :new, :create, :show] do
      resources :boards, only: [:index, :new, :create, :show] do
        resources :bookings, only: [:index, :new, :create, :show]
    end
  end

  namespace :users do
    resources :boards, only: [:index, :new, :create, :show]
    resources :bookings, only: [:index, :new, :create, :show] do
      member do
        patch :accept
        patch :refuse
      end
    end
  end
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user

  # has_many :customers, through: :bookings

  has_many :bookings
  # has_and_belongs_to_many :bookings

  has_one_attached :photo

  AVAILABILITY = ['Available', 'Booked', 'Over']

  BRAND = ['Quiksilver', 'Adams Surfboard', 'Decathlon', 'SEO']

  SIZE = [' 6″ – 6’8″', '6’8″ – 7’4″', '7’4″ – 8’6″', '8’6″ – 9’2″', '9’2″ – 9’6″', '+ de 9’6″']

  SHAPE = ['Fish', 'ShortBoard', 'Hybride', 'Funboard', 'Gunboard', 'Longboard']

    geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show]

  def index
    @user = current_user
    @boards = Board.all
    @owners = Owner.all
  end

  def new
    @board = Board.new
    @board.save
  end

  def create
    @user = current_user
    @board = Board.new(board_params)
    @board.user = @user
    # @board_photo = @board.photo
    @board.save
      redirect_to boards_path(@boards)
  end

  def show
    @bookings = Booking.all
    @booking = Booking.new
    @board = Board.find(params[:id])
    # @surfboard = Board.where(id: :id)
    @booking.board = @board
    # @booking.total_price = ((@booking.end_on - @booking.start_on) / 86_400) * @board.price
    if @booking.save
      redirect_to boards_path(board)
    else
      render 'boards/show'
    end
    # @others = Board.paginate(:page => params[:page], :per_page => 4).order('sort ASC')
  end

  private

  def set_board
    @boards = Board.all
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:name, :size, :brand, :shape, :guarantee_amount, :price, :contact,
    :description, :supplier_id, :address, :user_id, :owner_id, :photo)
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_info_window.html.erb
<h2><%= board.name %></h2>
<p><%= board.address %></p>

app/views/boards/create.html.erb
<div>
  <h1>Add a board</h1>
</div>

<div class="button">
  <%= link_to "Home", "/" %>
</div>
  <div class="container-body">
    <div class="col-6">
      <%= simple_form_for(@board) do |f| %>
        <div class="form-inputs">
          <%= f.input :name %>
          <%= f.input :size %>
          <%= f.input :brand %>
          <%= f.input :price %>
          <%= f.input :description %>
          <%= f.input :contact %>
        </div>
        <div class="form-actions">
          <%= f.button :submit, method: :post, class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>

app/views/boards/index.html.erb
<!-- <div class="title">
  <h1>See all the boards</h1>
</div>
 -->
<div class="container-body">
  <p>Heure locale <%= Time.now %> <%= Date.today %><p>
  <div class="index-boards-cards">
    <% @boards.each do |board| %>
      <div class="boards-cards">
        <div class="user-infos">
          <div class="user-details">
            <%= board.user.first_name %><br>
            <%= board.user.location %><br>
            <%= board.user.phone_number %><br>
          </div>
          <div class="user-photo">
            <img style="background-image: url('<%= cl_image_path board.user.photo.key %>')"><br>
          </div>
        </div>
          <hr style="width:90%", size="5", color=black>
        <div class="board-infos">
          <div class="board-details">
            <a><%= board.user.first_name %><br></a>
            <a><%  board.user.location %><br></a>
            <a><%= board.name %><br></a>
            <a><%= board.price %>€<br></a>
            <a><%= board.guarantee_amount %>€<br></a>
            <a><%= board.availability %><br></a>
          </div>
          <div class="board-photo">
            <img style="background-image: url('<%= cl_image_path board.photo.key %>')"><br>
          </div>
        </div>
        <div class="buttons">
          <div class="btn btn-warning">
            <%= link_to "Voir plus", board_path(board) %>
          </div>
          <div class="btn btn-warning">
            <%= link_to "Contact", board.user %>
          </div>
        </div>
        </div>
      <% end %>
  </div>
</div>

app/views/boards/new.html.erb
<div>
  <h1>Add a board</h1>
</div>

<div class="button">
  <%= link_to "Home", "/" %>
</div>
  <div class="container-body">
    <div class="col-6">
      <%= simple_form_for(@board) do |f| %>
        <div class="form-inputs">
          <%= f.input :name, placeholder: 'Donne un nom à ta planche' %>
          <%= f.input :price, placeholder: 'Prix de la location' %>
          <%= f.input :guarantee_amount, placeholder: 'Montant de la garantie' %>
          <%= f.label :size %>
          <%= f.select :size, Board::SIZE.each.map { |size| [size] } %>
          <%= f.label :shape %>
          <%= f.select :shape, Board::SHAPE.each.map { |shape| [shape] } %>
          <%= f.label :brand %>
          <%= f.select :brand, Board::BRAND.each.map { |brand| [brand] } %>
          <%= f.input :address %>
          <%= f.input :description, as: :text %>
          <%= f.input :contact %>
          <%= f.input :photo, as: :file, direct_upload: 'true' %>
        </div>
        <div class="form-actions">
          <%= f.button :submit, method: :post, class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>

app/views/boards/show.html.erb
    <h1 style="margin-left:100px;"><%= @board.name %><br>by <%= link_to @board.user.first_name, @board.user %></h1>
<div class="container-body" style="display:flex; margin-left:50px;">
  <div class="container-one-board" >
    <%= cl_image_tag @board.photo.key %>
    <div class="board-details">
      <a><%= @board.brand %><br></a>
      <a><%= @board.size %><br></a>
      <a><%= @board.supplier_id %><br></a>
      <a><%= @board.price %>€<br></a>
      <a><%= @board.address %><br></a>
    </div>
  </div>
  <div class="container" style="padding:20px;box-shadow: 2px 2px 10px 2px grey; margin-right:100px; border-radius:5px 5px 5px 5px;">
  <%= simple_form_for [@board, @booking], remote: true do |f| %>
    <div class="container_one">
      <%= f.collection_select :board_id, Board.all, :id, :name %>
      <%= f.input :start_on, as: :date %>
      <%= f.input :end_on, as: :date %>
      <%= f.submit "Book Now", class: "btn btn-primary" %>
    </div>
    <% end %>
  </div>
</div>