config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  devise_scope :user do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :new, :create, :show] do
    resources :boards, only: [:index, :new, :create, :show]
  end

  resources :boards, only: [:index, :show, :new, :create] do
    resources :users, only: [:index, :new, :create, :show]
  end

  resources :boards, only: [:index, :new, :create, :show] do
    resources :bookings, only: [:index, :new, :create, :show]
  end

  resources :users, only: [:index, :new, :create, :show] do
    resources :bookings, only: [:index, :new, :create, :show]
  end

  resources :bookings, only: [:index, :new, :create, :show] do
    resources :users, only: [:index, :new, :create, :show]
  end

  resources :users, only: [:index, :new, :create, :show] do
      resources :boards, only: [:index, :new, :create, :show] do
        resources :bookings, only: [:index, :new, :create, :show]
    end
  end

  namespace :users do
    resources :boards, only: [:index, :new, :create, :show]
    resources :bookings, only: [:index, :new, :create, :show] do
      member do
        patch :accept
        patch :refuse
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user

  # has_many :customers, through: :bookings

  has_many :bookings
  # has_and_belongs_to_many :bookings

  has_one_attached :photo

  AVAILABILITY = ['Available', 'Booked', 'Over']

  BRAND = ['Quiksilver', 'Adams Surfboard', 'Decathlon', 'SEO']

  SIZE = [' 6″ – 6’8″', '6’8″ – 7’4″', '7’4″ – 8’6″', '8’6″ – 9’2″', '9’2″ – 9’6″', '+ de 9’6″']

  SHAPE = ['Fish', 'ShortBoard', 'Hybride', 'Funboard', 'Gunboard', 'Longboard']

    geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/board_booking.rb
class BoardBooking < ApplicationRecord
  belongs_to :booking
  belongs_to :board
end

app/models/board_payment.rb
class BoardPayment < ApplicationRecord
  belongs_to :booking
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :board
  has_and_belongs_to_many :boards
  # validates :start_on, :end_on, presence: true #:total_price, :status,
  # validates :start_on, :end_on, format: { with: /([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]))/ }
  # # validates :total_price, numericality: true

  # belongs_to :board
  # accepts_nested_attributes_for :board

  # belongs_to :schedule
  # accepts_nested_attributes_for :schedule

  # belongs_to :owner
  # accepts_nested_attributes_for :owner

  # belongs_to :customer
  # accepts_nested_attributes_for :customer

  # has_many :board_payments, dependent: :destroy
  # accepts_nested_attributes_for :board_payments

  # validates :schedule_id, presence: true

  # has_many :booking_payments, dependent: :destroy
  # accepts_nested_attributes_for :booking_payments

  # enum status: [:pending, :completed, :cancelled]

  # scope :created_before, ->(time) { where('created_at < ?', time) }

  # Bookings cannot be in the past
  # def no_past_booking
  #   if Date.today > starts.to_date || Time.now > starts.to_time
  #     errors.add(:Starts, "cannot be in the past")
  #   elsif Date.today > ends.to_date || Time.now > ends.to-time
  #     errors.add(:Ends, "cannot be in the past")
  #   end
  # end


  # Validation for overlapping
  # def overlaps
  #   bookings = Bookings.where(room_id: id)
  #   bookings.each do |booking|
  #     if starts < booking.ends && booking.starts < ends
  #       errors.add(:overlaps, 'Already booked')
  #     end
  #   end
  # end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :bookings
  has_many :reviews

  belongs_to :user
  accepts_nested_attributes_for :user

  has_many :bookings, dependent: :destroy
  accepts_nested_attributes_for :bookings

  has_many :boards, :through => :bookings

  has_many :board_payments
end

app/models/owner.rb
class Owner < ApplicationRecord
  belongs_to :user
  accepts_nested_attributes_for :user

  has_many :boards

  has_many :board_payments, through: :bookings

  has_many :schedules, dependent: :destroy
  accepts_nested_attributes_for :schedules

  has_many :bookings, dependent: :destroy
  accepts_nested_attributes_for :bookings

  has_many :schedules, dependent: :destroy
  accepts_nested_attributes_for :schedules

  # mount_uploader :photo, TrainerUploader
  has_one_attached :photo
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer
  belongs_to :board

  enum state: [:not_reviewed, :published, :hidden]
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :owner, :inverse_of => :schedules
  accepts_nested_attributes_for :owner

  # belongs_to :customer
  # accepts_nested_attributes_for :customer

  has_many :bookings, :inverse_of => :schedule
  accepts_nested_attributes_for :bookings

  validates :start, uniqueness: { scope: :owner_id, message: "You have already made this time available" }

  # amoeba do
  #   enable
  #   exclude_associations :bookings
  # end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :boards
  has_many :users, through: :boards
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards
  has_many :bookings
  # has_many :board_bookings, through: :boards, source: :bookings

  has_one :owner, dependent: :destroy
  accepts_nested_attributes_for :owner

  # has_many :reviews

  has_one_attached :photo

  validates :first_name, :last_name, presence: true
  # validates :phone_number, uniqueness: true, numericality: { only_integer: true }
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  # include LocalTimeHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rent-a-Board</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <div class="container-buttons">
        <div class="btn btn-primary">
          <%= link_to "Home", root_path %>
        </div>
        <div class="btn btn-primary">
          <%= link_to "Communauté", boards_path %>
        </div>
        <div class="btn btn-primary">
          <%= link_to "Loue ta planche", new_board_path %>
        </div>
        <div class="btn btn-primary">
          <%= link_to "Spots", new_board_path %>
        </div>
      </div>
    <%= yield %>
    <div class="bg">
      <%= image_tag ("https://images.unsplash.com/photo-1515541324332-7dd0c37426e0?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1407&q=80")%>
      <div class="welcome-home-container">

      </div>
    </div>
  </body>
    <%= render 'shared/logo' %>
    <%= render 'shared/footer' %>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <p>Contact</p>
  <p>Anthony Mania</p>
  <p>Lite Services</p>
  <p>Agence Webdesign</p>
</div>

app/views/shared/_logo.html.erb
<div class="logo">
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <% end %>
    <div class="title">
      <h1>Rent-A-Board</h1>
      <p>Rent your surfboard from everywhere you are!</p>
    </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %><br>
      <div class="btn" style="width:500px">
          <%= form_tag boards_path, method: :get do %>
          <%= text_field_tag :query, params[:board],
          class: "form-control",
          placeholder: "Search"
        %>
        <%= submit_tag "OK", class: "btn" %>
      <% end %>
        </div>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
        <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profil", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item active">
          <p>Welcome <%= current_user.first_name %></p>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>